# Pipeline: https://dev.azure.com/dnceng/internal/_build?definitionId=1298

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*

pr: none

parameters:
- name: stabilizePackageVersion
  displayName: Stabilize package version
  type: boolean
  default: false
- name: publishToAzDO
  displayName: Publish to AzDO
  type: boolean
  default: false
- name: azDOPublishFeed
  displayName: AzDO publish feed
  type: string
  default: public/dotnet9-workloads
- name: publishToNuGet
  displayName: Publish to NuGet.org
  type: boolean
  default: false
- name: createVSInsertion
  displayName: Create VS insertion
  type: boolean
  default: false
- name: usePreComponentsForVSInsertion
  displayName: Use Preview Components for VS insertion
  type: boolean
  default: false
- name: includeNonShippingWorkloads
  displayName: Include non-shipping workloads
  type: boolean
  default: false
- name: vsTopicBranch
  displayName: 'VS Topic Branch [default: temp/{team}/{target}/yyyy-MM]'
  type: string
  default: '|default|'
- name: workloadDropNames
  displayName: Workload drop names
  type: object
  default:
  - emsdk
  - mono
# These insert (pre)components & packs into VS.
- name: primaryVsInsertionBranches
  displayName: Primary VS insertion branches
  type: object
  default:
  - rel/d17.12
# These insert packs only into VS [no (pre)components].
- name: secondaryVsInsertionBranches
  displayName: 'Secondary VS insertion branches [packs only]'
  type: object
  default: []

variables:
# Variables used: DncEngInternalBuildPool
- template: /eng/common/templates-official/variables/pool-providers.yml@self
############### ARCADE ###############
# Both this (used in Arcade for the MicroBuildSigningPlugin) and DotNetSignType (used in Arcade in Sign.proj) are necessary to set the sign type.
# https://github.com/dotnet/arcade/blob/ccae251ef033746eb0213329953f5e3c1687693b/Documentation/ArcadeSdk.md#common-steps-in-azure-devops-pipeline
- name: _SignType
  value: real
- name: _TeamName
  value: DotNet-Cli
- name: _BuildConfig
  value: Release
- name: PostBuildSign
  value: false
############### GROUPS ###############
# Provides TSA variables for automatic bug reporting.
- group: DotNet-CLI-SDLValidation-Params
# Release-Pipeline provides: BotAccount-dotnet-bot-repo-PAT, dn-bot-all-drop-rw-code-rw-release-all
# https://dnceng.visualstudio.com/internal/_library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=87&path=Release-Pipeline
- group: Release-Pipeline
# DotNet-DevDiv-Insertion-Workflow-Variables provides: dn-bot-devdiv-drop-rw-code-rw
# https://dnceng.visualstudio.com/internal/_library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=33&path=DotNet-DevDiv-Insertion-Workflow-Variables
- group: DotNet-DevDiv-Insertion-Workflow-Variables

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceAnalysisPool:
        name: $(DncEngInternalBuildPool)
        image: 1es-windows-2022
        os: windows
      policheck:
        enabled: true
      # Variables for TSA set within the DotNet-CLI-SDLValidation-Params variable group.
      tsa:
        enabled: true
    stages:
    - stage: Build
      displayName: Build
      jobs:
      - template: /eng/pipelines/templates/jobs/workload-build.yml@self
        parameters:
          stabilizePackageVersion: ${{ parameters.stabilizePackageVersion }}
          createVSInsertion: ${{ parameters.createVSInsertion }}
          usePreComponentsForVSInsertion: ${{ parameters.usePreComponentsForVSInsertion }}
          includeNonShippingWorkloads: ${{ parameters.includeNonShippingWorkloads }}
          vsTopicBranch: ${{ parameters.vsTopicBranch }}
          workloadDropNames: ${{ parameters.workloadDropNames }}
          primaryVsInsertionBranches: ${{ parameters.primaryVsInsertionBranches }}
          secondaryVsInsertionBranches: ${{ parameters.secondaryVsInsertionBranches }}
    - stage: Publish
      displayName: Publish
      dependsOn: Build
      jobs:
      - deployment: PublishFeed
        displayName: Publish to feed
        environment: DotNet-SDK-Workloads
        pool:
          name: $(DncEngInternalBuildPool)
          image: 1es-windows-2022
          os: windows
        templateContext:
          type: releaseJob
          isProduction: true
        strategy:
          runOnce:
            deploy:
              steps:
              - task: 1ES.DownloadPipelineArtifact@1
                displayName: 🟣 Download build artifacts
                inputs:
                  artifactName: Artifacts
                  targetPath: $(Build.SourcesDirectory)/artifacts
              # 1ES docs: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/outputs/nuget-packages
              # DotNetCoreCLI@2 docs: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2
              - ${{ if eq(parameters.publishToAzDO, true) }}:
                - task: 1ES.PublishNuget@1
                  displayName: 🟣 Publish packages to AzDO
                  inputs:
                    useDotNetTask: true
                    packagesToPush: $(Build.SourcesDirectory)/artifacts/packages/**/*.nupkg
                    packageParentPath: $(Build.SourcesDirectory)/artifacts
                    publishVstsFeed: ${{ parameters.feedForPublishing }}
              - ${{ if eq(parameters.publishToNuGet, true) }}:
                - task: 1ES.PublishNuget@1
                  displayName: 🟣 Publish packages to NuGet.org
                  inputs:
                    useDotNetTask: false
                    packagesToPush: $(Build.SourcesDirectory)/artifacts/packages/**/*.nupkg
                    packageParentPath: $(Build.SourcesDirectory)/artifacts
                    nuGetFeedType: external
                    publishVstsFeed: https://api.nuget.org/v3/index.json
                    # Service connection: https://dev.azure.com/dnceng/internal/_settings/adminservices?resourceId=479fdc43-a27d-4f5f-b2fc-5cf19dce159a
                    publishFeedCredentials: nuget.org (dotnetframework)
