# Pipeline: https://dev.azure.com/dnceng-public/public/_build?definitionId=264

pr:
  branches:
    include:
    - main
    - release/*
    - eng

trigger: none

resources:
  repositories:
  - repository: main
    type: github
    name: dotnet/workload-versions
    ref: refs/heads/main
    # https://dev.azure.com/dnceng-public/public/_settings/adminservices?resourceId=690f39b4-7746-42c2-be89-281bd7c78b9e
    endpoint: public
  - repository: release8
    type: github
    name: dotnet/workload-versions
    ref: refs/heads/release/8.0.4xx
    # https://dev.azure.com/dnceng-public/public/_settings/adminservices?resourceId=690f39b4-7746-42c2-be89-281bd7c78b9e
    endpoint: public
  - repository: release9
    type: github
    name: dotnet/workload-versions
    ref: refs/heads/release/9.0.1xx
    # https://dev.azure.com/dnceng-public/public/_settings/adminservices?resourceId=690f39b4-7746-42c2-be89-281bd7c78b9e
    endpoint: public

variables:
- template: /eng/pipelines/templates/variables/workload-public.yml@self
# Variables used: DncEngPublicBuildPool
- template: /eng/common/templates/variables/pool-providers.yml@main

stages:
- template: /eng/pipelines/templates/stages/workload-public-build.yml@self
  parameters:
    sourceBranchAlias: main
    engBranchAlias: self
- template: /eng/pipelines/templates/stages/workload-public-build.yml@self
  parameters:
    sourceBranchAlias: release8
    engBranchAlias: self
- template: /eng/pipelines/templates/stages/workload-public-build.yml@self
  parameters:
    sourceBranchAlias: release9
    engBranchAlias: self