# Pipeline: https://dev.azure.com/dnceng-public/public/_build?definitionId=264

pr:
  branches:
    include:
    - main
    - release/*

trigger: none

resources:
  repositories:
  - repository: eng
    type: github
    name: dotnet/workload-versions
    ref: refs/heads/eng
    # Service connection: https://dev.azure.com/dnceng-public/public/_settings/adminservices?resourceId=690f39b4-7746-42c2-be89-281bd7c78b9e
    endpoint: public

variables:
- template: /eng/pipelines/templates/variables/workload-public.yml@eng
# Variables used: DncEngPublicBuildPool
- template: /eng/common/templates/variables/pool-providers.yml@self

stages:
- template: /eng/pipelines/templates/stages/workload-public-build.yml@eng