# Pipeline: https://dev.azure.com/dnceng-public/public/_build?definitionId=264

pr:
  branches:
    include:
    - main
    - release/*

trigger: none

resources:
  repositories:
  - repository: eng
    type: github
    name: dotnet/workload-versions
    ref: refs/heads/eng

variables:
- template: /eng/pipelines/templates/variables/workload-public.yml@eng
# Variables used: DncEngPublicBuildPool
- template: /eng/common/templates/variables/pool-providers.yml@eng

stages:
# For checkout mechanics, see:
# https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services
# https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines
# https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#checkout-path
- checkout: self
  path: $(Pipeline.Workspace)/s
- checkout: eng
  path: $(Pipeline.Workspace)/s
- template: /eng/pipelines/templates/stages/workload-public-build.yml@eng