# Pipeline: https://dev.azure.com/dnceng-public/public/_build?definitionId=264

pr:
  branches:
    include:
    - main
    - release/*

trigger: none

resources:
  repositories:
  - repository: eng
    type: github
    name: dotnet/workload-versions
    ref: refs/heads/eng

variables:
- template: /eng/pipelines/templates/variables/workload-public.yml@eng
# Variables used: DncEngPublicBuildPool
- template: /eng/common/templates/variables/pool-providers.yml@eng

stages:
- template: /eng/pipelines/templates/stages/workload-public-build.yml@eng