jobs:
# Note: jobs.yml automatically includes the Publish Assets job for pushing the artifacts to DARC.
- template: /eng/common/templates-official/jobs/jobs.yml@source
  parameters:
    enableMicrobuild: true
    enablePublishBuildAssets: true
    enableTelemetry: true
    enablePublishUsingPipelines: true
    publishAssetsImmediately: true
    enableSbom: true
    repositoryAlias: source
    # This variable is evaluated when this job template is executed.
    # Therefore, the value will not be affected by the updatebuildnumber script below.
    officialBuildId: $[variables['Build.BuildNumber']]
    artifacts:
      publish:
        artifacts:
          name: Artifacts
        logs:
          name: Logs
        manifests: true
    jobs:
    - job: BuildRepo
      displayName: Build Repo
      timeoutInMinutes: 120
      pool:
        name: $(DncEngInternalBuildPool)
        image: 1es-windows-2022
        os: windows
      steps:
      - template: /eng/pipelines/templates/steps/workload-checkout.yml@self
        parameters:
          sourceBranchAlias: source
          engBranchAlias: self
      # Sets the run name to use the source branch commit message.
      # Also, sets the OfficialBuildId variable to the original Build.BuildNumber for use in Arcade.
      # See: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/run-number
      - powershell: |
          Write-Host "##vso[task.setvariable variable=OfficialBuildId]$(Build.BuildNumber)"
          Write-Host "##vso[task.setvariable variable=OfficialBuildIdFromJob;isoutput=true]$(Build.BuildNumber)"
          # Keep only valid characters. Invalid characters include: " / : < > \ | ? @ *
          # Also, strip any trailing '.' characters as those are invalid too.
          $commitMessage = "$(git log -1 --pretty=%s)".Trim() -replace '["\/:<>\\|?@*]|\.{1,}$', ''
          # Lastly, truncate to 255 max characters: 241 = 255 - 14 (for build number and delimiter, ex: 20250910.13 • )
          $commitMessage = $commitMessage.Substring(0, [Math]::Min($commitMessage.Length, 241))
          # If the build does not succeed, the run name will contain to what is set below.
          # If the build does succeed, Workloads.NET.Workloads.csproj will recreate the run name using OfficialBuildId, WorkloadsVersion, and SourceBranchCommitMessage.
          Write-Host "##vso[task.setvariable variable=SourceBranchCommitMessage]$commitMessage"
          Write-Host "##vso[build.updatebuildnumber]$(Build.BuildNumber) • $commitMessage"
        displayName: 🟣 Set run name via source branch commit message
        # Name is required to reference the variables created within this build step in other stages.
        name: SetRunName
      - ${{ if eq(parameters.createVSInsertion, true) }}:
        # The convertToJson expression in AzDO creates "pretty" JSON with line breaks and indentation.
        # To simplify passing this JSON to scripts, we collapse it to a single line.
        - powershell: |
            $workloadDropNames = @'
            ${{ convertToJson(parameters.workloadDropNames) }}
            '@
            $workloadListJson = $workloadDropNames -replace '\r?\n\s*', ''
            Write-Host "##vso[task.setvariable variable=WorkloadListJson]$workloadListJson"
          displayName: 🟣 Set WorkloadListJson variable
        - task: AzureCLI@2
          displayName: 🟣 Download workloads for VS insertion
          inputs:
            azureSubscription: DotNetStaging
            scriptType: pscore
            scriptPath: $(System.DefaultWorkingDirectory)/eng/download-workloads.ps1
            # Note: The second $ for usePreComponents and includeNonShipping allows the value to resolve as `$true` or `$false`.
            arguments: >-
              -workloadPath '$(System.DefaultWorkingDirectory)/artifacts/workloads'
              -gitHubPat (ConvertTo-SecureString -String '$(BotAccount-dotnet-bot-repo-PAT)' -AsPlainText -Force)
              -azDOPat (ConvertTo-SecureString -String '$(dn-bot-all-drop-rw-code-rw-release-all)' -AsPlainText -Force)
              -workloadListJson '$(WorkloadListJson)'
              -usePreComponents:$${{ parameters.usePreComponentsForVSInsertion }}
              -includeNonShipping:$${{ parameters.includeNonShippingWorkloads }}
      - powershell: eng/create-version-override.ps1
          -createTestWorkloadSet:$${{ parameters.createTestWorkloadSet }}
          -versionSdkMinor '${{ parameters.setVersionSdkMinor }}'
          -versionFeature '${{ parameters.setVersionFeature }}'
          -versionPatch '${{ parameters.setVersionPatch }}'
          -preReleaseVersionLabel '${{ parameters.setPreReleaseVersionLabel }}'
          -preReleaseVersionIteration '${{ parameters.setPreReleaseVersionIteration }}'
        displayName: 🟣 Create Version.Overrides.props
      # https://github.com/dotnet/arcade/blob/ccae251ef033746eb0213329953f5e3c1687693b/Documentation/CorePackages/Publishing.md#basic-onboarding-scenario-for-new-repositories-to-the-current-publishing-version-v3
      - powershell: >-
          eng/common/build.ps1
          -restore -build -sign -pack -publish -ci -msbuildEngine vs
          -configuration $(_BuildConfig)
          /p:CreateVSInsertion=${{ parameters.createVSInsertion }}
          /p:WorkloadDirectory=$(System.DefaultWorkingDirectory)/artifacts/workloads
          /p:DotNetSignType=$(_SignType)
          /p:TeamName=$(_TeamName)
          /p:DotNetPublishUsingPipelines=true
          /p:OfficialBuildId=$(OfficialBuildId)
          /p:StabilizePackageVersion=${{ parameters.stabilizePackageVersion }}
        displayName: 🟣 Build solution
        # Name is required to reference the variables created within this build step in other stages.
        name: BuildSolution
      - ${{ if eq(parameters.createVSInsertion, true) }}:
        - task: 1ES.PublishPipelineArtifact@1
          displayName: 🟣 Publish workload artifacts
          inputs:
            artifact: Workloads
            path: $(System.DefaultWorkingDirectory)/artifacts/workloads