parameters:
  sourceBranchAlias: self
  engBranchAlias: eng

stages:
- stage: Build_${{ parameters.sourceBranchAlias }}
  displayName: Build ${{ parameters.sourceBranchAlias }}
  dependsOn: []
  jobs:
  - template: /eng/common/templates/job/job.yml@${{ parameters.sourceBranchAlias }}
    parameters:
      name: buildRepo
      displayName: Build Repo
      pool:
        name: $(DncEngPublicBuildPool)
        demands: ImageOverride -equals windows.vs2022.amd64.open
      artifacts:
        publish:
          logs:
            name: Logs_${{ parameters.sourceBranchAlias }}
      steps:
      - template: /eng/pipelines/templates/steps/workload-checkout.yml@${{ parameters.engBranchAlias }}
        parameters:
          sourceBranchAlias: ${{ parameters.sourceBranchAlias }}
          engBranchAlias: ${{ parameters.engBranchAlias }}
      - powershell: >-
          eng/common/build.ps1
          -restore -build -pack -ci -msbuildEngine vs
          -configuration $(_BuildConfig)
          /p:DotNetSignType=$(_SignType)
          /p:TeamName=$(_TeamName)
        displayName: 🟣 Build solution